{
 "title": "kafka monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Total Match Results Processed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "spring_kafka_template_seconds_count{name=\"kafkaTemplate\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Producer Success Rate",
   "type": "stat",
   "description": "System Health",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(spring_kafka_template_seconds_count{result=\"success\"} > 0) or vector(1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Message Send Latency",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "spring_kafka_template_seconds_sum{name=\"kafkaTemplate\"} / spring_kafka_template_seconds_count{name=\"kafkaTemplate\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messages Sent Per Second",
   "type": "timeseries",
   "description": "Rate of badminton match results sent to Kafka",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(spring_kafka_template_seconds_count{name=\"kafkaTemplate\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messages Processed Per Second (by Consumer)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (name) (spring_kafka_listener_seconds_count)"
    }
   ]
  },
  {
   "title": "Messages Processed by Consumer Group",
   "type": "timeseries",
   "description": "Consumer Groups Activity",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "spring_kafka_listener_seconds_count",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Connection Pool Overview",
   "type": "stat",
   "gridPos": { "h": 9, "w": 10, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jdbc_connections_max{name=\"dataSource\"}      # Max connections\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "jdbc_connections_idle{name=\"dataSource\"}     # Idle connections  \n",
     "legendFormat": "__auto"
    },
    {
     "expr": "jdbc_connections_active{name=\"dataSource\"}   # Active connections",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}